### ISSUE TITLE
Error when saving answers to conditional questions

### ISSUE THREAD

**Issue by verarojman** [Platoniq/decidim-indices#98]
## Description of the error

There is an error when processing responses to questions from a survey that are conditionally displayed, causing them not to be saved in the database.

Responses are being sent correctly in the `POST` request, so the issue is located in the backend.

More precisely, the responses saved in the browser's Local Storage, under the key `awesome_autosave:edit_questionnaire_140` from where they're fetched before sending them to the server. This is a feature from the `decidim_awesome` module. There is another local storage key `awesome_autosave:checkboxes:edit_questionnaire_140`, that stores whether the responses to checkboxes have a custom body.

With the string stored in `awesome_autosave:edit_questionnaire_140` in local storage, you can do the following to easily store its contents as a JSON:

```ruby
params_string = File.read("wherever-you-saved-that-string.txt")
decoded_params = URI.decode_www_form(params_string)
File.write("local-storage-params.json", decoded_params.to_h.to_json)
```

After correctly being sent to the `Decidim::Forms::QuestionnaireForm` (in the `HasQuestionnaire` controller concern's `answer` method), answer choices to questions that are conditionally displayed, seem to be lost in the ocean.

## Where is the error happening
💡  The error is most probably in `Decidim::Forms::AnswerForm`, maybe something to do with the `display_conditions_fulfilled?` method.
 

> **Note:** The custom SAT developments don't seem to be interfering.

### A. Load production database

A1. Drop current development database
`rails db:drop db:create`

A2. Load production database dump (download it from the server via ssh)
`psql -h localhost -U decidim -d indices_development -f xxxxxxxxxxxx-indices.pgsql`

A3. Change organization host to localhost

```ruby
# rails console

Decidim::Organization.first.update(host: "localhost")`
```

### B. Create a new user and sign in

```ruby
# rails console

Decidim::User.create!(
  email: "your-user@example.org",
  nickname: "your-user",
  name: "Your User",
  password: "Decidim123456789",
  password_confirmation: "Decidim123456789",
  confirmed_at: Time.now,
  organization: Decidim::Organization.first,
  tos_agreement: true
)
```

### C. Visit http://localhost:3000/processes/satEnumerate/f/131/#

C1. Fill in the form

C2. Submit the form

C3. Check that the answers to conditional questions were not saved:

```ruby
# rails console

answers = Decidim::Forms::Answer.where(user: Decidim::User.last)
answer_choices = Decidim::Forms::AnswerChoice.where(answer: answers)
```

## List of conditional question IDs

Depending on input from **question 432**:
- `[433, 435, 437, 438, 439, 440]`

Depending on input from **question 455**:
- `[456, 462, 463, 457, 464]`
- `[461, 465, 466]`
- `[489]`

Depending on input from **question 469**:
- `[470, 472, 473, 474]`
- `[476, 477, 478, 479]`
- `[482, 483, 484, 485, 486]`
- `[490, 491]`

Depending on input from **question 474**:
- `[475]`

**Comment by rafaelpoza** [comment]
### Update and resolution

This issue was introduced through the PR (https://github.com/Platoniq/decidim-indices/pull/75) which tried to save the form answers without raising errors if a mandatory question was not filled (see task in https://app.asana.com/0/1201751562918741/1202312036019931/f).

The development carried out did not validate the form responses, and that made the responses were not present in the context (used by the Rectify gem) when the validations checked if an optional response meets all the requirements/conditions to be filled.

![image](https://user-images.githubusercontent.com/16348967/200816267-4bbc49fe-4e7e-4d19-b7e6-d337f7cec1df.png)

After the PR which allows to solve partially a form, the team introduced other developments which made that work in the browser/client side, using JavaScript and local storage, and that deprecated the origin of this error, but it was not rolled back.

The piece of code which stars this issue is **app/lib/decidim/overrides/forms/answer_questionnaire.rb**, and it was rolled back with the PR (https://github.com/Platoniq/decidim-indices/pull/104). After applying this solution, we found that **non sat_set forms failed due to a double-render error**. That was produced by a call to the parent method which makes the same thing as the current inherit method. This bug was solved in commit (https://github.com/Platoniq/decidim-indices/commit/faebd9d44bdd1ce161d5ed19d3b188e5658bf86c), removing that override and letting that feature similar to the version which introduced this issue.

### Another solution (workaround)

In parallel, another team was working on this issue and reached another solution without rolling back the PR#75. What they made was introduce the responses into the context scope, manually, without Rectify gem intervention. 

After a deep debugging process, we discovered the responses reach the backend, but they were pulled out form context due to the form were not validated (this validation is carried out in Rectify, but that team did not know this info).

![image](https://user-images.githubusercontent.com/16348967/200892256-bf1454cc-a252-4926-a9fa-4c8056695196.png)

That discovery was found once we inspected the line 55. Before the _select_ method, all the responses were there, but after that, they were missing. So, before process the _display_conditions_fulfilled?_ method (in _form_factory_ when the context is initalized), we add them to the context scope manually in order to have them in the method when we need to check if they should be filled or not.

This development is saved in the commit (https://github.com/Platoniq/decidim-indices/commit/414388be074967e9cf438a6cfcba7e253f762c40)

![image](https://user-images.githubusercontent.com/16348967/200825176-0352e7ca-b4a9-4036-aacc-d64975dcddbe.png)


This solution is not as clear nor accurate as the final one, but it could be helpful for futher developments
